services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - sitmun-network-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sitmun3
      POSTGRES_USER: sitmun3
      POSTGRES_PASSWORD: sitmun3
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sitmun3"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3

networks:
  sitmun-network-postgres:
    driver: bridge