databaseChangeLog:
  - include:
      file: changelog/01_schema.h2.sql
      relativeToChangelogFile: true
  - include:
      file: changelog/02_codelists.yaml
      relativeToChangelogFile: true
  - include:
      file: changelog/03_task_types.yaml
      relativeToChangelogFile: true
  - include:
      file: changelog/04_data.yaml
      relativeToChangelogFile: true
  - include:
      file: changelog/05_translations.yaml
      relativeToChangelogFile: true
  - include:
      file: changelog/06_params.yaml
      relativeToChangelogFile: true