services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    restart: unless-stopped
    networks:
      - sitmun-network-oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: password
      APP_USER: sitmun3
      APP_USER_PASSWORD: sitmun3
      ORACLE_DATABASE: sitmun3
    healthcheck:
      test: |
        bash -c '
        lsnrctl status | grep -q "Service \"sitmun3\"" &&
        echo "SELECT 1 FROM DUAL;" | sqlplus -s sitmun3/sitmun3@//localhost:1521/sitmun3 | grep -q "1"
        '
      interval: 5s
      timeout: 5s
      start_period: 60s
      retries: 20

networks:
  sitmun-network-oracle:
    driver: bridge